#ifndef CONTROLSCOMMON_H
#define CONTROLSCOMMON_H


enum GRAPHICSITEMTYPE{
    GRAPHICSITEMTYPE_HANDLERECT=10000,
    GRAPHICSITEMTYPE_RECT=10001,
    GRAPHICSITEMTYPE_TARGETSEARCH=10002,
    GRAPHICSITEMTYPE_BACKGROUNDIMAGE=10003,
    GRAPHICSITEMTYPE_TEXT=10004,
    GRAPHICSITEMTYPE_DISTANCE=10005,
    GRAPHICSITEMTYPE_ARROW=10006,
};

#endif // CONTROLSCOMMON_H
